### ISSUE TITLE
Vue.use在typescript4报错

### ISSUE THREAD

**Issue by SplendorJiang** [lin557/vue-video-monitor#1]
在typescript 4.x环境中main.ts如下引入会报错
`import VueVideoMonitor from 'vue-video-monitor'

Vue.use(VueVideoMonitor)` 

![图片](https://user-images.githubusercontent.com/63274923/196612973-3cd3727f-f595-4537-8674-b444923967ad.png)

可能要把index.js改成
`import VueVideoMonitor from './vue-video-monitor.vue'
// 注册组件
export default {
  install(Vue) {
    Vue.component(VueVideoMonitor.name, VueVideoMonitor)
  }
}`

**Comment by lin557** [comment]
正在编写typescript+vue3版本
https://github.com/lin557/v3d-monitor
